# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: Camine

steps:
- task: CmdLine@2
  inputs:
    script: |
      ls
      cd src
      ls

- task: DockerCompose@0
  displayName: 'Run Docker Compose'
  inputs:
    action: 'Build services'
    dockerComposeFile: 'build/docker-compose.yml'
    projectName: 'nobilauto'
    buildImages: true
- task: DockerCompose@0
  displayName: 'Down Docker Compose'
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeFile: 'build/docker-compose.yml'
    projectName: 'nobilauto'
    dockerComposeCommand: 'down --remove-orphans'
- task: DockerCompose@0
  displayName: 'Up Docker Compose'
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeFile: 'build/docker-compose.yml'
    projectName: 'nobilauto'
    dockerComposeCommand: 'up'
    arguments: '-d'
